### ISSUE TITLE
x-if combination

### ISSUE THREAD

**Issue by ericxin1982** [mgschoen/alpine-editable#1]
Hi @mgschoen 

Is it any example I can read if this plug-in works with x-if some variable, since I think there is a button like edit, once edit button clicked then this feature can be on or click div cannot make div editable right?

Thanks
Eric Xin

**Comment by mgschoen** [comment]
Hi @ericxin1982! Thanks for your question. Not sure if I understand correctly, but in general the plugin works inside x-if too, yes. Are you looking for something like this?

```html
<div x-data="{ value: 'Edit me!', isEditable: false }">
    <input type="checkbox" x-model="isEditable">
    <template x-if="isEditable">
        <div x-editable="value"></div>
    </template>
</div>
```

Feel free to give an example of what you're trying to achieve and I'll try to help!

**Comment by ericxin1982** [comment]
![image](https://github.com/mgschoen/alpine-editable/assets/9047436/51f8883f-6a80-494b-a78f-9c0b4488bc07)
![image](https://github.com/mgschoen/alpine-editable/assets/9047436/d385e746-6532-4555-84de-3ea92f5de542)
![image](https://github.com/mgschoen/alpine-editable/assets/9047436/5bb8de55-4684-4ed7-9f48-e9a40660983f)

Hi @mgschoen 

If you use that way, then the div is totally not there if iseditable is false, what I meant is the div is there, but cannot be click to edit, I saw your project, and I try to reach the similar way, can you see the code, see if that is possible to add switch to control the x-editable behavior like that way.

Thanks
Eric Xin

**Comment by mgschoen** [comment]
@ericxin1982 Thanks for the example, understood. What you could do right now is programmatically replace `x-editable` with `x-text` when `xeditable` changes to `false`. I tested in this codepen and it seems to work: https://codepen.io/mgschoen/pen/mdgLxdX.

But I agree this is not very handy. I'll see if I can update the library to provide toggling editability.

**Comment by ericxin1982** [comment]
![image](https://github.com/mgschoen/alpine-editable/assets/9047436/4f926f89-20ca-4e7c-8d54-073c42c55f3f)
It does not work well for x-text removed, and the way you use is too much coding work there even if it works.

**Comment by mgschoen** [comment]
Hi @ericxin1982, feel free to take a look at [version 1.1.0](https://github.com/mgschoen/alpine-editable/releases/tag/v1.1.0). It includes a simplified way to disable/enable editing, like this:

```html
<div
    x-data="{
        value: 'Edit me!',
        isEditable: false,
    }"
>
    <span
        x-editable="value"
        x-editable:disabled="!isEditable"
        @editable-change="value = $el.innerHTML"
    ></span>
    <button
        x-text="isEditable ? 'Lock' : 'Edit'"
        @click="isEditable = !isEditable"
    ></button>
</div>
```

I've updated the CodePen accordingly: https://codepen.io/mgschoen/pen/mdgLxdX

**Comment by ericxin1982** [comment]
That is a nice update, this version can be used in production environment out of box. Thanks!

**Comment by ericxin1982** [comment]
Can you share with me suspend, how to use, and why that exists, although I may not need it now.

**Comment by ericxin1982** [comment]
Hi @mgschoen 

Sorry to bother you again.
When I should use suspend, when I should use disable.
And the dispatch event, it is more attractive, would you please create some examples and put them in github, and all we can learn, I am pretty sure it is a great plugin in future if it has detailed doc.

Thanks
Eric Xin

**Comment by mgschoen** [comment]
Hey @ericxin1982, please refer to the editable.js docs for questions about when to use what. As documented, `x-editable:disabled` uses editable.js methods [`disable()`](https://github.com/livingdocsIO/editable.js/blob/master/src/core.js#L130) and [`enable()`](https://github.com/livingdocsIO/editable.js/blob/master/src/core.js#L151). `x-editable:suspended` uses [`suspend()`](https://github.com/livingdocsIO/editable.js/blob/master/src/core.js#L175) and [`continue()`](https://github.com/livingdocsIO/editable.js/blob/master/src/core.js#L192).
