### ISSUE TITLE
Just wondering why the cdn.min.js is that big

### ISSUE THREAD

**Issue by ericxin1982** [mgschoen/alpine-editable#3]
Hi @mgschoen 

I am curious why this editable plug-in is so big, which is even bigger than alpinejs itself.

Thanks
Eric Xin

**Comment by mgschoen** [comment]
Hi @ericxin1982, the CDN build includes the entire editable.js Library. This ensures that `@livingdocs/editable.js` and `alpine-editable` are always compatible. The plugin code itself is just 113 lines of code and consists of exactly one file: https://github.com/mgschoen/alpine-editable/blob/main/src/index.js

**Comment by ericxin1982** [comment]
Oh, I see.
